### ISSUE TITLE
backward compatibility support for SDK

### ISSUE THREAD

**Issue by taarsh** [CommvaultEngg/cvpysdk#45] opened 2018-07-25 09:42 UTC
Hello team,

I would like to know about backward compatibility support with new versions of SDK.
we are using CVSP13 sdk for our automation, can you let us know if i can use this SDK for testing older CV versions like CVsp10, CVsp11 etc?

we are facing below error when i am using CVSP13 sdk on my CV11SP10 test machines. Everything else is working fine, APIs related to media agents are not working.

Would be great if you could give backward compatibility support so that we dont need to change our test cases with the SDK versions you release.

<snip>
>>> commcell.media_agents._get_media_agents()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/appeng/Public/cvpysdk-SP13/cvpysdk/commcell.py", line 630, in media_agents
    self._media_agents = MediaAgents(self)
  File "/home/appeng/Public/cvpysdk-SP13/cvpysdk/storage.py", line 141, in __init__
    self.refresh()
  File "/home/appeng/Public/cvpysdk-SP13/cvpysdk/storage.py", line 295, in refresh
    self._media_agents = self._get_media_agents()
  File "/home/appeng/Public/cvpysdk-SP13/cvpysdk/storage.py", line 215, in _get_media_agents
    raise SDKException('Response', '102')
cvpysdk.exception.SDKException: Response received is empty 
</snip>

**Comment by GoelJatin** [comment] 2018-07-26 05:38
Hi @taarsh ,

We do support backward compatibility.

In the above case, you shouldn't be calling the **private** methods from your code. 

Please try:

`>>> print(commcell.media_agents)`
`>>> print(commcell.media_agents.all_media_agents)`

Please do let us know if you face any situation where you feel the code is not backward compatible, and we'll try to get it fixed ASAP.

Best Regards!
Jatin

**Comment by GoelJatin** [comment] 2018-07-26 09:41
Hi @Anu-26 / @taarsh ,

I'll check this shortly and get back to you.

Can you confirm how many media agents are listed on the console?

**Comment by GoelJatin** [comment] 2018-07-26 09:49
Hi @taarsh / @Anu-26 ,

Can you also share the output of executing this API call on your setup.

API Endpoint: V2/MediaAgents

You can either try from Postman / from SDK directly:

`>>> response = commcell.request('GET', 'V2/MediaAgents')`
`>>> print(response.text)`
`>>> print(response.json)`

This would be helpful for me to confirm the exact issue.

**Comment by Anu-26** [comment] 2018-07-26 11:07
Hi Jatin,

Below is the output  by running form SDK.
>>> response = commcell.request('GET', 'V2/MediaAgents')
>>> print(response.text)
}errorMessage":"Internal Error. This function is not yet implemented.","errorCode":1
>>> print(response.json())
{'error': {'errorMessage': 'Internal Error. This function is not yet implemented.', 'errorCode': 1}}
>>>
>>> print(response)
<Response [200]>
>>> print(response.text)
}errorMessage":"Internal Error. This function is not yet implemented.","errorCode":1
>>>

**Comment by GoelJatin** [comment] 2018-07-26 12:39
Thanks @Anu-26 

The issue is because a new API was implemented for getting the list of Media Agents, with additional information, as due to some restrictions, same could not be added to the existing API.

And this API was added around SP12.

Which is why the API call on an SP10 setup is failing.

Perhaps you can use the SDK shipped as part of the DVD for the same service pack, to ensure compatibility, as from our end we always ensure that none of the SDK Classes / Methods interface should be changed in any Service Pack.

And any changes in the SDK code should not affect any scripts / applications written on top of it.

Above operations should be working with SDK from any SP12 or lower tree.

Please let us know if you need any more information.

**Comment by GoelJatin** [comment] 2018-08-06 07:04
Conclusion: Please use the SDK version shipped with the Commvault Software DVD.

Closing the issue.

**Comment by ozskywalker** [comment] 2018-08-06 12:29
Wouldn't it be possible to add extra boilerplate code to check if the CommServe is compatible with that call, which would allow for the SDK to be backwards compatible?  If you have to manage multiple commcells that may be at different service packs, you could end up having to use different SDK versions just to command & control those cells.

**Comment by GoelJatin** [comment] 2018-08-07 11:07
Hi @ozskywalker ,

Thanks for the suggestion.

We discussed this and came to the conclusion to check for the API compatibility, and use the appropriate API.

Going forward, we are going to ensure that SDK is always backward compatible with all Commcells.

Although it won't be possible right now to do the same for the Media Agents API.

We can try to do it for any future Service Pack.

If you or anyone else ever sees this issue again, do let us know, and we'll get it fixed.

Re-opening this issue to keep track.

**Comment by klogan12** [comment] 2019-01-08 07:31
Lets reopen this if someone hit the same issue again.

**Closed by klogan12** 2019-01-08 07:31 UTC
Labels: tracker
